MyLib/ViewModels/Report/ReportIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyLib.ViewModels.Report
{
    public class ReportIndexModel
    {
        public PageViewModel PageViewModel { get; set; }
        public IEnumerable<ReportViewModel> Reports { get; set; }
    }
}

MyLib/ViewModels/Report/ReportViewModel.cs
using System;

namespace MyLib.ViewModels.Report
{
    public class ReportViewModel
    {
        public int ReportId { get; set; }

        //Atributes
        public int ReportReason { get; set; }
        public string ReportDescription { get; set; }
        public DateTime ReportDate { get; set; }
        public bool ReportIsRead { get; set; } //уведомление админу/модеру

        //FKs Comment
        public int CommentId { get; set; }
        public DateTime CommentCreated { get; set; }
        public string CommentContent { get; set; }

        public string CommentAuthorId { get; set; }
        public string CommentAuthorFullName { get; set; }

        public int PostId { get; set; }
        public string PostTitle { get; set; }
        //FKs UserReporter
        public string UserReporterId { get; set; }
        public string UserReporterFullName { get; set; }
    }
}

MyLib/Controllers/ReportController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyLib.Data.Models;
using MyLib.Services.Interfaces;
using MyLib.ViewModels;
using MyLib.ViewModels.Report;
using System.Linq;
using System.Threading.Tasks;

namespace MyLib.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReport _reportService;
        private readonly UserManager<User> _userManager;

        public ReportController(UserManager<User> userManager, IReport reportService)
        {
            _reportService = reportService;
            _userManager = userManager;
        }
        public ActionResult Index(int page = 1)
        {
            //if (User.IsInRole("MainAdmin"))
            //{
                int pageSize = 10;
                var reports = _reportService.GetAll().Where(x => !x.IsRead).ToList();

                var reportsOnPage = reports.Select(rep => new ReportViewModel
                {
                    ReportId = rep.Id,
                    ReportReason = rep.Reason,
                    ReportDescription = rep.Description,
                    ReportDate = rep.ReportDate,
                    CommentId = rep.Comment.Id,
                    CommentCreated = rep.Comment.Created,
                    CommentContent = rep.Comment.Content,
                    CommentAuthorId = rep.Comment.User.Id,//нулль
                    CommentAuthorFullName = rep.Comment.User.FullName,//нулль
                    UserReporterId = rep.UserReporter.Id,
                    UserReporterFullName = rep.UserReporter.FullName
                }).Skip((page - 1) * pageSize).Take(pageSize).ToList();

                PageViewModel pageViewModel = new PageViewModel(reports.Count(), page, pageSize, null);

                var model = new ReportIndexModel
                {
                    PageViewModel = pageViewModel,
                    Reports = reportsOnPage
                };
                return View(model);
            //}
           //else return RedirectToAction("Account", "AccessDenied");
        }

        [HttpPost]
        public async Task <IActionResult> CheckReport(int id)
        {
            //if (User.IsInRole("MainAdmin"))
            //{
            var rep =  _reportService.GetById(id);
            await _reportService.CheckReport(rep);
                
            return RedirectToAction("Index");
            //}
            //else return RedirectToAction("Account", "AccessDenied");
        }

        //[HttpPost]
        public ActionResult GetCountReports()
        {
            var reports = _reportService.CountUnread();
            return Json(reports);
        }
    }
}

MyLib/Views/Report/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model MyLib.ViewModels.Report.ReportIndexModel
@addTagHelper *, MyLib
@{ 
    string ConvertReason(int r)
    {
        string result = "";
        switch (r)
        {
            case 1:
                result = "Спам, мошенничество";
                break;
            case 2:
                result = "Непристойное поведение";
                break;
            case 3:
                result = "Пропаганда экстремизма";
                break;
            case 4:
                result = "Иное";
                break;
        }
        return result;
    }
    var reps = Model.Reports.ToList();
 }

<div class="container myCase">
    <div class="row no-gutters pb-2 mb-2" id="cluster-head">
        <div class="col-12">
            <h3>Непрочитанные жалобы</h3>
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-12 col-md-8 pr-md-3" id="cluster-list">
            <div id="accordion">
                @if (Model.Reports.Count() == 0)
                {
                    <h3>Необработанных жалоб нет</h3>
                }
                @for (int i = 0; i < Model.Reports.Count(); i++)
                {
                    <div class="card mb-2">
                        <div class="card-header card-clustering" id="headingOne">
                            <div class="d-flex flex-row align-items-center justify-content-between">
                                <div>
                                    <h5 class="mb-0">
                                        <button class="btn btn-light" data-toggle="collapse" data-target="@("#collapse" + i)" aria-expanded="false" aria-controls="@("#collapse" + i)">
                                            <h1>@("Жалоба №" + (i + 1))</h1>
                                        </button>
                                    </h5>
                                </div>
                                <div>
                                    <form asp-controller="Report" asp-action="CheckReport" asp-route-id="@reps[i].ReportId" method="post">
                                        <button type="submit" class="btn btn-primary">Обработать</button>
                                    </form>
                                </div>        
                            </div>
                        </div>
                        <div id="@("collapse" + i)" class="collapse" aria-labelledby="@("heading" + i)">
                            <div class="card-body">
                                <div class="row mb-2 pb-2" id="book-card">
                                    <div class="col-12">
                                        <div>
                                            <p>
                                                Пользователь <a asp-controller="Profile"
                                                                asp-action="Index"
                                                                asp-route-id="@reps[i].CommentAuthorId">
                                                    @reps[i].CommentAuthorFullName
                                                </a>
                                                оставил следующий комментарий:
                                            </p>
                                            <blockquote class="blockquote">
                                                @reps[i].CommentContent
                                            </blockquote>
                                            <p>
                                                Пользователь <a asp-controller="Profile"
                                                                asp-action="Index"
                                                                asp-route-id="@reps[i].UserReporterId">
                                                    @reps[i].UserReporterFullName
                                                </a>
                                                посчитал данный комментарий недопустимым по следующей причине:
                                            </p>
                                            <blockquote class="blockquote">
                                                @ConvertReason(reps[i].ReportReason)
                                            </blockquote>
                                                <p>Также, пользователь оставил комментарий:</p>
                                                <blockquote class="blockquote">
                                                    @reps[i].ReportDescription
                                                </blockquote>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <page-link page-model="Model.PageViewModel" page-action="Index"></page-link>
        </div>
    </div>
</div>