MyLib/Controllers/BookController.cs
using k_clustering.Utilities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyLib.Data.Models;
using MyLib.Services.Interfaces;
using MyLib.ViewModels;
using MyLib.ViewModels.Book;
using MyLib.ViewModels.Tag;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace MyLib.Controllers
{
    public class BookController : Controller
    {
        private readonly IBook _bookService;
        private readonly IRating _ratingService;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        private readonly Regex _regex = new Regex("([ \\t{}()\",:;. \n])");

        public BookController(IBook bookService,
            IRating ratingService,
            UserManager<User> userManager,
            IWebHostEnvironment hostingEnvironment)
        {
            _bookService = bookService;
            _ratingService = ratingService;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Index", new { searchQuery });
        }

        public IActionResult Index(string searchQuery, int page = 1)
        {
            int pageSize = 3;
            var books = _bookService.GetFilteredBooks(searchQuery).OrderByDescending(x => x.PublicationDate).ToList();
            var noResults = !string.IsNullOrEmpty(searchQuery) && !books.Any();

            var booksOnPage = books
                .Select(book => new BookViewModel
                {
                    BookId = book.Id,
                    Title = book.Title,
                    ImageUrl = book.ImageUrl,
                    Author = book.Author,
                    Genre = book.Genre,
                    Rating = book.Rating,
                    PublicationDate = book.PublicationDate,
                    UserId = book.User.Id,
                    Year = book.Year,
                    Description = book.Description,
                    Tags = book.BookTags.Where(bt => bt.BookId == book.Id).ToList().Select(bt => new TagViewModel
                    {
                        Id = bt.Tag.Id,
                        Name = bt.Tag.Name,
                        Type = bt.Tag.Type
                    })
                }).Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(books.Count(), page, pageSize, searchQuery);

            var model = new BookIndexModel()
            {
                Books = booksOnPage,
                PageViewModel = pageViewModel,
                SearchQuery = searchQuery
            };

            List<int> rates = new List<int>();
            foreach (var book in booksOnPage)
                rates.Add(_ratingService.GetAll().Where(x => x.Book.Id == book.BookId).ToList().Count);

            ViewBag.Rates = rates;

            return View(model);
        }

        public IActionResult Detail(int id, int page = 1)
        {            
            var book = _bookService.GetById(id);
            var genres = book.Genre.ToLower().Split(new char[] { ',', ' ' }).ToList();
            int pageSize = genres.Contains("поэзия") || genres.Contains("пьеса") ? 50 : 25;

            var rates = _ratingService.GetAll().Where(x => x.Book.Id == id).ToList().Count;
            ViewBag.Rates = rates;

            var bookTags = book.BookTags.Where(bt => bt.BookId == id).ToList();

            var tags = bookTags
                .Select(bt => new TagViewModel
                {
                    Id = bt.Tag.Id,
                    Name = bt.Tag.Name,
                    Type = bt.Tag.Type
                });

            var sentences = book.Content.Split(new char[] { '\n' }).ToList();
            var chapters = book.Content.Split(new char[] { '|' }).ToList();

            List<string> headings = new List<string>();
            foreach (var chapter in chapters)
                headings.Add(chapter.Split(new char[] { '\n' }).FirstOrDefault());

            for (int i = 0; i < sentences.Count - 1; i++)
            {
                if (sentences[i] == "\r" && sentences[i + 1] == "\r")
                {
                    sentences.RemoveAt(i + 1);
                    i--;
                }
            }

            var paginText = sentences.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(sentences.Count, page, pageSize, null);

            ViewBag.Heads = headings.Count;

            var model = new BookViewModel
            {
                BookId = id,
                Title = book.Title,
                Content = book.Content,
                PublicationDate = book.PublicationDate,
                Year = book.Year,
                Status = book.Status,
                ImageUrl = book.ImageUrl,
                Description = book.Description,
                Author = book.Author,
                Genre = book.Genre,
                Isbn = book.ISBN,
                Rating = book.Rating,
                UserId = book.User.Id,
                Tags = tags,
                Pages = pageViewModel,
                Sentences = headings.Count > 1 ? headings : paginText
            };

            ViewBag.IsVoted = _ratingService.IsBookRated(book.Id, _userManager.GetUserId(User));

            return View(model);
        }

        public IActionResult Read(int id, int chapter, int page = 1)
        {
            var book = _bookService.GetById(id);
            var genres = book.Genre.ToLower().Split(new char[] { ',', ' ' }).ToList();
            int pageSize = genres.Contains("поэзия") || genres.Contains("пьеса") ? 50 : 25;

            var rates = _ratingService.GetAll().Where(x => x.Book.Id == id).ToList().Count;
            ViewBag.Rates = rates;

            var bookTags = book.BookTags.Where(bt => bt.BookId == id).ToList();

            var tags = bookTags
                .Select(bt => new TagViewModel
                {
                    Id = bt.Tag.Id,
                    Name = bt.Tag.Name,
                    Type = bt.Tag.Type
                });

            //begin хрень
            var chapters = book.Content.Split(new char[] { '|' }).ToList();

            var content = chapters[chapter];
            var sentences = content.Split(new char[] { '\n' }).ToList();

            for (int i = 0; i < sentences.Count - 1; i++)
            {
                if (sentences[i] == "\r" && sentences[i + 1] == "\r")
                {
                    sentences.RemoveAt(i + 1);
                    i--;
                }
            }

            var paginText = sentences.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(sentences.Count, chapter, page, pageSize);

            var model = new BookViewModel
            {
                BookId = id,
                Title = book.Title,
                Content = book.Content,
                PublicationDate = book.PublicationDate,
                Year = book.Year,
                Status = book.Status,
                ImageUrl = book.ImageUrl,
                Description = book.Description,
                Author = book.Author,
                Genre = book.Genre,
                Isbn = book.ISBN,
                Rating = book.Rating,
                UserId = book.User.Id,
                Tags = tags,
                Pages = pageViewModel,
                Sentences = paginText
            };

            ViewBag.IsVoted = _ratingService.IsBookRated(book.Id, _userManager.GetUserId(User));

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RateBook(BookViewModel model)
        {
            var book = _bookService.GetById(model.BookId);
            var userId = _userManager.GetUserId(User);
            if (userId == null)
            {
                {
                    ViewBag.ErrorMessage = $"Пользователь с Id : {userId} не может быть найден";
                    return NotFound();
                }
            }
            var user = _userManager.FindByIdAsync(userId).Result;

            if (_ratingService.IsBookRated(book.Id, userId))
            {
                return RedirectToAction("Index");
            }

            var newBookRate = new Rating
            {
                BookRate = model.RateValue,
                Book = book,
                User = user
            };

            await _ratingService.Add(newBookRate);

            book.Rating = _ratingService.CalculateBookRating(book.Id);

            await _bookService.Edit(book);

            return RedirectToAction("Detail", new { id = model.BookId });
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBook(BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                if (userId == null)
                {
                    ViewBag.ErrorMessage = $"Пользователь с Id : {userId} не может быть найден";
                    return NotFound();
                }

                var user = _userManager.FindByIdAsync(userId).Result;

                string imgUrl = UploadBookImage(model);
                var bookContent = ExtractTextFromFile(model);
                var transformText = TransformText(bookContent);

                var newBook = new Book
                {
                    Title = model.Title,
                    Author = model.Author,
                    Description = model.Description,
                    Genre = model.Genre,
                    Year = model.Year,
                    ImageUrl = imgUrl,

MyLib/Controllers/UserController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyLib.Data.Models;
using MyLib.Services.Interfaces;
using MyLib.ViewModels.UserProfile;
using System.IO;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace MyLib.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IUser _userService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IBook _bookService;
        private readonly IForum _forumService;
        private readonly IComment _commentService;
        private readonly SignInManager<User> _signInManager;
        private readonly IRating _ratingService;

        public UserController(IUser userService,
            UserManager<User> userManager,
            IWebHostEnvironment hostingEnvironment, 
            IBook bookService, IForum forumService, IComment commentService,
            SignInManager<User> signInManager,
            IRating ratingService)
        {
            _userService = userService;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
            _bookService = bookService;
            _forumService = forumService;
            _commentService = commentService;
            _signInManager = signInManager;
            _ratingService = ratingService;
        }

        /*public async Task<IActionResult> Detail(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMassage = $"Не найден пользователь с Id = {id}";
                return NotFound();
            }

            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new UserProfileViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                FullName = user.FullName,
                Age = user.Age,
                Email = user.Email,
                ExistingImageUrl = user.ProfileImageUrl,
                Phone = user.PhoneNumber,
                UserRating = user.Rating,
                UserRoles = userRoles,
                IsAdmin = userRoles.Contains("Admin")
            };

            return View(model);
        }*/

        [HttpPost] //Заменил ГЕТ на ПОСТ, чтоб уж наверняка никто в будущем не хакнул никого)))
        public async Task<IActionResult> Detail(UserProfileViewModel model)
        {
            if (_userManager.GetUserId(User) == model.UserId)
            {
                var user = await _userManager.FindByIdAsync(model.UserId);

                /*if (user == null)
                {
                    ViewBag.ErrorMassage = $"Не найден пользователь с Id = {id}";
                    return NotFound();
                }*/

                var userRoles = await _userManager.GetRolesAsync(user);

                var model2 = new UserProfileViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    FullName = user.FullName,
                    Age = user.Age,
                    Email = user.Email,
                    ExistingImageUrl = user.ProfileImageUrl,
                    Phone = user.PhoneNumber,
                    UserRating = user.Rating,
                    UserRoles = userRoles,
                    IsAdmin = userRoles.Contains("Admin")
                };

                return View(model2);
            }
            else return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditProfile(UserProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.UserId);

                if (user == null)
                {
                    ViewBag.ErrorMassage = $"Не найден пользователь с Id = {model.UserId}";
                    return NotFound();
                }
                else
                {
                    user.FullName = model.FullName;
                    user.Email = model.Email;
                    user.Age = model.Age;
                    user.PhoneNumber = model.Phone;
                    user.ProfileImageUrl = UploadProfileImage(model) ?? user.ProfileImageUrl;
                }
                
                await _userService.Edit(user);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProfile(string id)
        {
            if (id == null)
            {
                ViewBag.ErrorMassage = $"Не найден пользователь с Id = {id}";
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (!user.IsDeleted)
                user.IsDeleted = true;

            await _userManager.UpdateAsync(user);

            await _signInManager.SignOutAsync(); // иначе исключение

            return RedirectToAction("Index", "Home");
        }

        private string UploadProfileImage(UserProfileViewModel model)
        {
            if (model.Image != null)
            {
                var uploadsFolder = _hostingEnvironment.WebRootPath + "\\images\\profile";
                var fileUrl = model.Image.FileName;
                var filePath = Path.Combine(uploadsFolder, fileUrl);
                var stream = new FileStream(filePath, FileMode.Create);
                model.Image.CopyTo(stream);
                stream.Close();

                return @"/images/profile/" + fileUrl;
            }

            return null;
        }

        public async Task<IActionResult> Profile(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user.IsDeleted)
                return RedirectToAction("Index", "Home");
            else
            {
                var books = _bookService.GetAll().ToList();
                ViewBag.BooksQuantity = books.Where(x => x.User.Id == id).ToList().Count;
                var posts = _forumService.GetAll().ToList();
                ViewBag.PostsQuantity = posts.Where(x => x.User.Id == id).ToList().Count;
                var comments = _commentService.GetAll().ToList();
                ViewBag.CommentsQuantity = comments.Where(x => x.User.Id == id).ToList().Count;

                var bestThreeBooks = books.Where(x => x.User.Id == id).OrderByDescending(x => x.Rating).ToList().Take(3);
                ViewBag.BestThreeBooks = bestThreeBooks.ToList();

                List<int> rates = new List<int>();
                foreach (var book in bestThreeBooks)
                    rates.Add(_ratingService.GetAll().Where(x => x.Book.Id == book.Id).ToList().Count);

                ViewBag.Rates = rates;

                if (user == null)
                {
                    ViewBag.ErrorMassage = $"Не найден пользователь с Id = {id}";
                    return NotFound();
                }

                var userRoles = await _userManager.GetRolesAsync(user);

                var model = new UserProfileViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    FullName = user.FullName,
                    Age = user.Age,
                    Email = user.Email,
                    ExistingImageUrl = user.ProfileImageUrl,
                    Phone = user.PhoneNumber,
                    UserRating = user.Rating,
                    UserRoles = userRoles,
                    IsAdmin = userRoles.Contains("Admin")
                };

                return View(model);
            }

        }
    }
}

MyLib/Views/User/Detail.cshtml
@model MyLib.ViewModels.UserProfile.UserProfileViewModel
@{
    ViewBag.Title = "Профиль пользователя";
    var imagePath = Model.ExistingImageUrl ?? "/images/profile/noprofileimage.png";
}

<div class="container myCase">
    <h2>Профиль пользователя</h2><hr />
    <h3>Здесь вы можете изменить параметры вашей учетной записи</h3><hr />
    <div class="col-md-6">
        <form method="post" enctype="multipart/form-data"
              asp-controller="User" asp-action="EditProfile">
            <div class="form-group">
                <label class="col-form-label" asp-for="Image">Аватарка</label>
                <div class="custom-file">
                    <input asp-for="Image" class="form-control custom-file-input" onchange="readURL(this)"/>
                    <label class="custom-file-label image-file">Выберите изображение...</label>
                </div>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="col-form-label row no-gutters" asp-for="ExistingImageUrl">Текущая аватарка</label>
                <img id="image" src="@imagePath" class="booksImageEdit" asp-append-version="true" />
            </div>
            <div class="form-group row no-gutters">
                <label class="col-sm-2 col-form-label" asp-for="FullName"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="FullName" />
                    <span class="text-danger field-validation-valid"
                          asp-validation-for="FullName"></span>
                </div>
            </div>
            <div class="form-group row no-gutters">
                <label class="col-sm-2 col-form-label" asp-for="Age"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Age" />
                    <span class="text-danger field-validation-valid"
                          asp-validation-for="Age"></span>
                </div>
            </div>            <div class="form-group row no-gutters">
                <label class="col-sm-2 col-form-label" asp-for="Phone"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Phone" />
                    <span class="text-danger field-validation-valid"
                          asp-validation-for="Phone"></span>
                </div>
            </div>            <div class="form-group row no-gutters">
                <label class="col-sm-2 col-form-label" asp-for="Email"></label>
                <div class="col-sm-10">
                    <input class="form-control" asp-for="Email" />
                    <span class="text-danger field-validation-valid"
                          asp-validation-for="Email"></span>
                </div>
            </div>
            <input type="hidden" asp-for="UserId" />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group row no-gutters">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Обновить профиль</button>
                </div>
            </div>
        </form>
        <form asp-action="DeleteProfile" asp-route-id="@Model.UserId" method="post">
            <button type="submit" class="btn btn-danger"
                    onclick="return confirm('Вы точно хотите удалить свой профиль? В случае подтверждения его никак нельзя будет восстановить!')">
                Удалить профиль
            </button>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $('.custom-file-label').html(fileName);
            });
        })
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#image')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

MyLib/Views/User/Profile.cshtml
@model MyLib.ViewModels.UserProfile.UserProfileViewModel
@using Microsoft.AspNetCore.Identity
@using MyLib.Data.Models
@inject UserManager<MyLib.Data.Models.User> UserManager
@{
    ViewBag.Title = Model.FullName;
    var btb = ViewBag.BestThreeBooks;
    string ConvertDate(DateTime date)
    {
        TimeSpan timeDifference = DateTime.Now - date;
        if (timeDifference.TotalDays > 365)
            return date.ToString();
        else
        if (timeDifference.TotalDays > 31)
        {
            int months = (int)timeDifference.TotalDays / 31;
            if (months == 1) return $"{months} месяц назад";
            else if (months <= 4) return $"{months} месяца назад";
            else return $"{months} месяцев назад";
        }
        else
        if (timeDifference.TotalDays > 1)
        {
            int decs = (int)timeDifference.TotalDays / 10;
            int solo = (int)timeDifference.TotalDays % 10;
            if (decs == 1)
                return $"{Math.Floor(timeDifference.TotalDays)} дней назад";
            else
            {
                if (solo == 1) return $"{Math.Floor(timeDifference.TotalDays)} день назад";
                else if (solo >= 2 && solo <= 4) return $"{Math.Floor(timeDifference.TotalDays)} дня назад";
                else return $"{Math.Floor(timeDifference.TotalDays)} дней назад";
            }
        }
        else
        if (timeDifference.TotalHours > 1)
        {
            int decs = (int)timeDifference.TotalHours / 10;
            int solo = (int)timeDifference.TotalHours % 10;
            if (decs == 1)
                return $"{Math.Floor(timeDifference.TotalHours)} часов назад";
            else
            {
                if (solo == 1) return $"{Math.Floor(timeDifference.TotalHours)} час назад";
                else if (solo >= 2 && solo <= 4) return $"{Math.Floor(timeDifference.TotalHours)} часа назад";
                else return $"{Math.Floor(timeDifference.TotalHours)} часов назад";
            }
        }
        else
        if (timeDifference.TotalMinutes > 1)
        {
            int decs = (int)timeDifference.TotalMinutes / 10;
            int solo = (int)timeDifference.TotalMinutes % 10;
            if (decs == 1)
                return $"{Math.Floor(timeDifference.TotalMinutes)} минут назад";
            else
            {
                if (solo == 1) return $"{Math.Floor(timeDifference.TotalMinutes)} минута назад";
                else if (solo >= 2 && solo <= 4) return $"{Math.Floor(timeDifference.TotalMinutes)} минуты назад";
                else return $"{Math.Floor(timeDifference.TotalMinutes)} минут назад";
            }
        }
        else
            return "меньше минуты назад";
    }
}
<div class="container myCase">
    <div class="row no-gutters userStat">
        <div class="col-4 col-md-3 pr-3">
            <div class="nav-item d-block mb-2">
                <a class="nav-link item-responsive item-1by1" style="padding-right: 0px;padding-bottom: 0px;padding-left: 0px;" asp-controller="User" asp-action="Profile" asp-route-id="@Model.UserId">
                    <img class="content" src="@Model.ExistingImageUrl" />
                </a>
            </div>
        </div>
        <div class="col-8 col-md-9 pl-3">
            <div class="d-flex flex-column usercard">
                <div class="nav-item d-block mb-1">
                    <a class="" asp-controller="User" asp-action="Profile" asp-route-id="@Model.UserId">
                        @Model.FullName
                    </a>
                </div>
                <div class="nav-item d-block mb-1">
                    Загружено книг: @ViewBag.BooksQuantity
                </div>
                <div class="nav-item d-block mb-1">
                    Создано тем: @ViewBag.PostsQuantity
                </div>
                <div class="nav-item d-block mb-1">
                    Комментариев: @ViewBag.CommentsQuantity
                </div>
            </div>
        </div>
    </div>

    <h3>Топ-3 книг, загруженных пользователем</h3>
    <div class="row no-gutters">
        @for (int i = 0; i < btb.Count; i++)
        {
            <div class="col-12 mb-2">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title overflow">"@btb[i].Title" (@btb[i].Author)</h5>
                    </div>
                    <div class="card-body pb-2">
                        <div class="row">
                            <div class="col-12 pr-0">
                                <div class="d-flex flex-column justify-content-between p-0">
                                    <div class="mb-2">Жанр: <b>@btb[i].Genre</b></div>
                                    <div class="mb-2">Год публикации произведения: <b>@btb[i].Year</b></div>
                                    <div class="text-muted">Опубликована на сайте:</div>
                                    <div class="mb-2 text-muted">@ConvertDate(btb[i].PublicationDate)</div>
                                    <div class="mb-2 overflow">@btb[i].Description</div>
                                    <div class="d-flex flex-column flex-md-row mb-2">
                                        <div>Рейтинг произведения: </div>
                                        <div class="">@btb[i].Rating / 5 (голосов: @ViewBag.Rates[i])</div>
                                    </div>
                                    @if (btb[i].User.Id == UserManager.GetUserId(User))
                                    {
                                        <div class="mb-2">
                                            <a asp-action="Edit" asp-route-id="@btb[i].Id" class="btn btn-success">
                                                Редактировать
                                            </a>
                                        </div>
                                        <div class="mb-2">
                                            <form asp-action="Delete" asp-route-id="@btb[i].Id" method="post">
                                                <button type="submit" class="btn btn-danger"
                                                        onclick="return confirm('Вы точно хотите удалить книгу &quot;@btb[i].Title&quot;?')">
                                                    Удалить
                                                </button>
                                            </form>
                                        </div>
                                    }
                                    <div id="card-btn" class="pb-1 mb-2">
                                        <div>
                                            <a asp-controller="Book" asp-action="Detail" asp-route-id="@btb[i].Id" class="btn btn-primary">
                                                Перейти к чтению
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>