MyLib/ViewModels/Clustering/ClusteringResultsViewModel.cs
using k_clustering.k_means.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyLib.ViewModels.Clustering
{
    public class ClusteringResultsViewModel
    {
        public List<List<ClusteringBookViewModel>> BookClusters { get; set; }
        public List<int> ClusterIds { get; set; }
        public List<int> BookIds { get; set; }
        public List<bool> BookChecks { get; set; }
        public List<int> BookChecksInt { get; set; }
        public List<int> TagIds { get; set; }
        public List<int> TagChecksInt { get; set; }
        public List<ClusteringTagViewModel> Tags { get; set; }
    }
}

MyLib/Controllers/ClusterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using k_clustering.k_means;
using k_clustering.k_means.Objects;
using k_clustering.TextClustering;
using k_clustering.TextClustering.SimilarityMetrics;
using k_clustering.Utilities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyLib.Clustering.TextClustering;
using MyLib.Clustering.TextClustering.MLObjects;
using MyLib.Data.Models;
using MyLib.Services.Interfaces;
using MyLib.ViewModels.Clustering;

namespace MyLib.Controllers
{
    public class ClusterController : Controller
    {
        private readonly IBook _bookService;
        private readonly ITag _tagService;
        private readonly IRating _ratingService;
        private readonly UserManager<User> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        private readonly Regex _regex = new Regex("([ \\t{}()\",:;. \n])");

        public ClusterController(IBook bookService,
            ITag tagService,
            IRating ratingService,
            UserManager<User> userManager,
            IWebHostEnvironment hostingEnvironment)
        {
            _bookService = bookService;
            _tagService = tagService;
            _ratingService = ratingService;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpPost]
        public IActionResult Search(string searchQueryName, string searchQueryTag)
        {
            return RedirectToAction("Index", new { searchQueryName, searchQueryTag });
        }

        public IActionResult Index(string searchQueryName, string searchQueryTag)
        {
            var books = _bookService.GetFilteredBooks(searchQueryName).ToList();
            var booksWithTags = _bookService.GetBookWithTags(books, searchQueryTag).ToList();

            var bookModel = booksWithTags
                .Select(book => new ClusteringBookViewModel
                {
                    BookId = book.Id,
                    Title = book.Title,
                    ImageUrl = book.ImageUrl,
                    Content = book.Content,
                    ProcessedText = book.ProcessedText,
                    PortedText = book.PortedText,
                    Tags = book.BookTags,
                    Author = book.Author
                }).ToList();

            var tags = _tagService.GetAll().ToList();

            var tagModel = tags
                .Select(tag => new ClusteringTagViewModel
                {
                    Id = tag.Id,
                    Name = tag.Name,
                    Type = tag.Type
                }).ToList();

            var model = new ClusteringIndexViewModel()
            {
                Books = bookModel,
                Tags = tagModel,
                BookChecks = Enumerable.Repeat(true, bookModel.Count).ToList()
            };

            ViewBag.Books = model.Books;
            return View(model);
        }

        [HttpGet]
        public IActionResult ClusteringResults(ClusteringResultsViewModel model)
        {
            return View(model);
        }

        [HttpPost]
        public IActionResult ClusteringResults(ClusteringIndexViewModel model)
        {
            var books = model.BookIds.Select((id, index) =>  (model.BookChecksInt[index] == 1) ? _bookService.GetById(id) : null).Where(elem => elem!=null);

            List<Cluster> clusters;

            if (!model.MLNet)
            {
                DocumentVectorModel documentVectorModel = new DocumentVectorModel(false);
                documentVectorModel.CreateDVCollection(books.Select(book
                    => book.ProcessedText).ToList(), books.Select(book
                    => book.Id).ToArray());

                K_means kMeans = new K_means(new CosineSimilarity());

                if (model.XMeans)
                    clusters = kMeans.XCluster(documentVectorModel.DocumentVectorCollection);
                else
                    clusters = kMeans.Cluster(documentVectorModel.DocumentVectorCollection, model.K);
            }
            else
            {
                var mLBooks = books.Select(book => new MLBook
                {
                    Id = book.Id,
                    Text = Regex.Replace(book.Content.ToLower(), @"[^ а-я]", string.Empty)  
                });


                MLClustering mLClustering = new MLClustering();

                clusters = mLClustering.Cluster(mLBooks, model.K);
            }

            var bookClusters = new List<List<ClusteringBookViewModel>>();

            foreach (var cluster in clusters)
            {
                bookClusters.Add(new List<ClusteringBookViewModel>());

                for (int i = 0; i < cluster.DocumentGroup.Count; i++)
                {
                    Book book = _bookService.GetById(cluster.DocumentGroup[i].Id);

                    var bookModel = new ClusteringBookViewModel()
                    {
                        BookId = book.Id,
                        Author = book.Author,
                        Title = book.Title,
                        ImageUrl = book.ImageUrl,
                        Content = book.Content,
                        ProcessedText = book.ProcessedText,
                        PortedText = book.PortedText,
                        Tags = book.BookTags.OrderBy(tag=>tag.Tag.Type)
                    };

                    bookClusters.Last().Add(bookModel);
                }
            }

            var tagsModel = _tagService.GetAll().Select(tag => new ClusteringTagViewModel
            {
                Id = tag.Id,
                Name = tag.Name,
                Type = tag.Type
            }).ToList();

            var viewModel = new ClusteringResultsViewModel()
            {
                BookClusters = bookClusters,
                Tags = tagsModel,
                BookChecks = Enumerable.Repeat(true, books.Count()).ToList()
            };


            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddTags(ClusteringResultsViewModel model)
        {
            var books = model.BookIds.Select((id, index) => (model.BookChecksInt[index] == 1) ? _bookService.GetById(id) : null).Where(book => book != null).ToList();

            await Task.Delay(1000);

            var tags = model.TagIds.Select((id, index) => (model.TagChecksInt[index] == 1) ? _tagService.GetById(id) : null).Where(tag => tag != null).ToList();

            await Task.Delay(1000);

            foreach (var tag in tags)
            {
                foreach (var book in books)
                {
                    await _tagService.AddTagToBook(book, tag);
                }
            }

            await Task.Delay(1000);

            var allBooks = model.BookIds.Select(id => _bookService.GetById(id)).ToList();

            var bookClusters = new List<List<ClusteringBookViewModel>>();


            int temp = model.ClusterIds[0];
            bookClusters.Add(new List<ClusteringBookViewModel>());
            for (int i = 0; i < model.ClusterIds.Count; i++)
            {
                if (temp != model.ClusterIds[i])
                    bookClusters.Add(new List<ClusteringBookViewModel>());

                temp = model.ClusterIds[i];

                Book book = allBooks[i];

                var bookModel = new ClusteringBookViewModel()
                {
                    BookId = book.Id,
                    Author = book.Author,
                    Title = book.Title,
                    ImageUrl = book.ImageUrl,
                    Content = book.Content,
                    ProcessedText = book.ProcessedText,
                    PortedText = book.PortedText,
                    Tags = book.BookTags.OrderBy(tag => tag.Tag.Type)
                };

                bookClusters.Last().Add(bookModel);
            }

            var tagsModel = _tagService.GetAll().Select(tag => new ClusteringTagViewModel
            {
                Id = tag.Id,
                Name = tag.Name,
                Type = tag.Type
            }).ToList();

            var viewModel = new ClusteringResultsViewModel()
            {
                BookClusters = bookClusters,
                Tags = tagsModel,
                BookChecks = Enumerable.Repeat(true, books.Count()).ToList()
            };

            return View("ClusteringResults", viewModel);
        }

        //Legendary
        [HttpPost]
        public async Task<IActionResult> DeleteTags(ClusteringResultsViewModel model)
        {
            var books = model.BookIds.Select((id, index) => (model.BookChecksInt[index] == 1) ? _bookService.GetById(id) : null).Where(book => book != null).ToList();

            await Task.Delay(1000);

            var tags = model.TagIds.Select((id, index) => (model.TagChecksInt[index] == 1) ? _tagService.GetById(id) : null).Where(tag => tag != null).ToList();

            await Task.Delay(1000);

            foreach (var tag in tags)
            {
                foreach (var book in books)
                {
                    await _tagService.RemoveTagFromBook(book, tag);
                }
            }

            await Task.Delay(1000);

            var allBooks = model.BookIds.Select(id => _bookService.GetById(id)).ToList();

            var bookClusters = new List<List<ClusteringBookViewModel>>();

            int temp = model.ClusterIds[0];
            bookClusters.Add(new List<ClusteringBookViewModel>());
            for (int i = 0; i < model.ClusterIds.Count; i++)
            {
                if (temp != model.ClusterIds[i])
                    bookClusters.Add(new List<ClusteringBookViewModel>());

                temp = model.ClusterIds[i];

                Book book = allBooks[i];

                var bookModel = new ClusteringBookViewModel()
                {

MyLib/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using MyLib.Data.Models;
using MyLib.Services.Interfaces;
using MyLib.ViewModels.Tag;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyLib.Controllers
{
    public class TagController : Controller
    {
        private readonly ITag _tagService;
        private readonly IBook _bookService;

        public TagController(ITag tagService, IBook bookService)
        {
            _tagService = tagService;
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            var tags = _tagService.GetAll();
            return View(tags);
        }

        public IActionResult CreateTag()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTag(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newTag = new Tag
                {
                   Name = model.Name,
                   Type = model.Type,
                };

                await _tagService.Add(newTag);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [Route("Tag/DeleteTag/{tagId}")]
        public async Task<IActionResult> DeleteTag(int tagId)
        {
            var tag = _tagService.GetById(tagId);
            if (tag == null)
            {
                ViewBag.ErrorMassage = $"Не найден тег с Id = {tagId}";
                return NotFound();
            }
            else
            {
                await _tagService.Delete(tag.Id);

                return RedirectToAction("Index");
            }
        }

        [Route("Tag/EditTag/{tagId}")]
        public IActionResult EditTag(int tagId)
        {
            var tag = _tagService.GetById(tagId);
            if (tag == null)
            {
                ViewBag.ErrorMassage = $"Не найден тег с Id = {tagId}";
                return NotFound();
            }

            List<BookTagsViewModel> booksWithTagViewModel = new List<BookTagsViewModel>();

            foreach (var book in _bookService.GetAll())
            {
                if (book.BookTags.Select(bt => bt.Tag.Id == tag.Id).Contains(true))
                {
                    booksWithTagViewModel.Add(new BookTagsViewModel
                    {
                        BookId = book.Id,
                        BookTitle = book.Title,
                        BookImageUrl = book.ImageUrl
                    });
                }
            }

            var model = new TagViewModel
            {
                Id = tag.Id,
                Name = tag.Name,
                Type = tag.Type,
                Books = booksWithTagViewModel
            };

            return View(model);
        }

        [HttpPost]
        [Route("Tag/EditTag/{Id}")]
        public async Task<IActionResult> EditTag(TagViewModel model)
        {
            var tag = _tagService.GetById(model.Id);
            if (tag == null)
            {
                ViewBag.ErrorMassage = $"Не найден тег с Id = {model.Id}";
                return NotFound();
            }
            else
            {
                tag.Name = model.Name;
                tag.Type = model.Type;

                await _tagService.Edit(tag);

                return RedirectToAction("Index");
            }
        }

        [Route("Tag/AddTagsToBook/{tagId}")]
        public IActionResult AddTagsToBook(int tagId)
        {
            var tag = _tagService.GetById(tagId);
            if (tag == null)
            {
                ViewBag.ErrorMassage = $"Не найден тег с Id = {tagId}";
                return NotFound();
            }

            ViewBag.tagName = tag.Name;
            ViewBag.tagId = tagId;

            var model = new List<BookTagsViewModel>();
            var books = _bookService.GetAll();

            foreach (var book in books)
            {
                var bookTagsModel = new BookTagsViewModel
                {
                    BookId = book.Id,
                    BookTitle = book.Title,
                    BookImageUrl = book.ImageUrl,
                    BookAuthor = book.Author
                };

                if (book.BookTags.Any(bt => bt.Tag.Id == tag.Id))
                {
                    bookTagsModel.IsSelected = true;
                }
                else
                {
                    bookTagsModel.IsSelected = false;
                }

                model.Add(bookTagsModel);
            }

            return View(model);
        }

        [HttpPost]
        [Route("Tag/AddTagsToBook/{tagId}")]
        public async Task<IActionResult> AddTagsToBook(List<BookTagsViewModel> model, int tagId)
        {
            var tag = _tagService.GetById(tagId);
            if (tag == null)
            {
                ViewBag.ErrorMassage = $"Не найден тег с Id = {tagId}";
                return NotFound();
            }

            for (int i = 0; i < model.Count; i++)
            {
                var book = _bookService.GetById(model[i].BookId);

                if (model[i].IsSelected)
                {
                    await _tagService.AddTagToBook(book, tag);

                }
                else if (!model[i].IsSelected)
                {
                    await _tagService.RemoveTagFromBook(book, tag);
                }
                else
                {
                    continue;
                }

                if (i < model.Count - 1)
                    continue;
                else
                    return RedirectToAction("EditTag", new { Id = tagId });
            }

            return RedirectToAction("EditTag", new { Id = tagId });
        }
    }
}

MyLib/Views/Cluster/ClusteringResults.cshtml
@model MyLib.ViewModels.Clustering.ClusteringResultsViewModel

<div class="container myCase">
    <div class="row no-gutters pb-2 mb-2" id="cluster-head">
        <div class="col-md-8">
            <div class="d-flex flex-column flex-md-row justify-content-between">
                <div>
                    <h3>Результаты кластеризации</h3>
                </div>
                <div>
                    <a asp-action="Index" class="rounded btn btn-dark">Назад к кластеризации</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row no-gutters">
        <div class="col-12 col-md-8 pr-md-3" id="cluster-list">
            <div id="accordion">
                @for (int i = 0; i < Model.BookClusters.Count; i++)
                {
                    <div class="card mb-2">
                        <div class="card-header card-clustering" id="headingOne">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h5 class="mb-0">
                                        <button class="btn btn-light" data-toggle="collapse" data-target="@("#collapse" + i)" aria-expanded="false" aria-controls="@("#collapse" + i)">
                                            <h1>@("Кластер №" + (i+1))</h1>
                                        </button>
                                    </h5>
                                </div>
                                <div class="d-flex justify-content-center">
                                    <div><input type="checkbox" name="@("cluster" + i)" class="chk-all form-control" style="width: 40px; height: 40px;" onclick="ChangeAll('@i')" checked/></div>
                                    <div class="ml-2 align-self-center">Выбрать все</div>
                                </div>
                            </div>
                        </div>
                        @for (int j = 0; j < Model.BookClusters[i].Count; j++)
                        {
                            <div id="@("collapse" + i)" class="collapse" aria-labelledby="@("heading" + i)">
                                <div class="card-body">
                                    <div class="row mb-2 pb-2" id="book-card">
                                        <div class="col-2">
                                            <a asp-controller="Book" asp-action="Detail" asp-route-id="@Model.BookClusters[i][j].BookId">
                                                <img class="booksImageCell" src="@Model.BookClusters[i][j].ImageUrl" />
                                            </a>
                                        </div>
                                        <div class="col-8 bl-1px-s-ddd br-1px-s-ddd">
                                            <div>
                                                <p id="bookTitle">@Model.BookClusters[i][j].Author</p>
                                                <p id="bookTitle">@Model.BookClusters[i][j].Title</p>
                                            </div>
                                            <div class="tags d-flex flex-column flex-md-row">
                                                @foreach (var tag in Model.BookClusters[i][j].Tags)
                                                {
                                                    <div class="mb-2 mb-md-0 mr-md-2">
                                                        @if (tag.Tag.Type == MyLib.Data.Models.TagType.Author)
                                                        {
                                                            <a asp-controller="Tag" asp-action="EditTag" asp-route-id="@tag.Tag.Id"
                                                               class="btn p-2 text-light" style="background-color: rgb(127, 21, 136);">
                                                                @tag.Tag.Name
                                                            </a>
                                                        }
                                                        else if (tag.Tag.Type == MyLib.Data.Models.TagType.Genre)
                                                        {
                                                            <a asp-controller="Tag" asp-action="EditTag" asp-route-id="@tag.Tag.Id"
                                                               class="btn p-2 text-light" style="background-color: rgb(231, 61, 46);">
                                                                @tag.Tag.Name
                                                            </a>
                                                        }
                                                        else if (tag.Tag.Type == MyLib.Data.Models.TagType.All)
                                                        {
                                                            <a asp-controller="Tag" asp-action="EditTag" asp-route-id="@tag.Tag.Id"
                                                               class="btn p-2 text-light" style="background-color: rgb(32, 125, 122);">
                                                                @tag.Tag.Name
                                                            </a>
                                                        }
                                                    </div>
                                                }
                                            </div>
                                        </div>
                                        <div class="col-2 d-flex flex-column align-self-center">
                                            <input id="@("checkVisible" + i + j)" type="checkbox" asp-for="@Model.BookChecks[i]" class="form-control" name="@("cluster" + i)" onclick="checkChange('@i' + '@j')"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                }
            </div>
            <page-link page-model="Model.PageViewModel" page-action="Index"></page-link>
        </div>

        <div class="col-12 col-md-4 pl-md-3">
            <div class="row no-gutters mt-2">
                <div class="col">
                    <button class="btn btn-primary" onclick="showAdd()">Добавление</button>
                </div>
                <div class="col">
                    <button class="btn btn-danger" onclick="showDelete()">Удаление</button>
                </div>
            </div>

            <div id="add" class="mt-2">
                <form asp-controller="Cluster" asp-action="AddTags" method="post">
                    @foreach (var tag in Model.Tags)
                    {
                        <input asp-for="TagIds" value="@tag.Id" hidden />
                        <input class="@("tagCheckHidden" + tag.Id)" name="TagChecksInt" asp-for="TagChecksInt" value="-1" hidden />
                        <div class="d-flex flex-row align-items-center mb-2">
                            <div><input type="checkbox" class="form-control @("addCheckbox" + tag.Id)" onclick="addTagCheckChange('@tag.Id')" style="width:50px;" /></div>
                            <div><label>@tag.Name</label></div>
                        </div>                                      
                    }
                    @for (int i = 0; i < Model.BookClusters.Count; i++)
                    {
                        for (int j = 0; j < Model.BookClusters[i].Count; j++)
                        {
                            <input asp-for="ClusterIds" value="@i" hidden />
                            <input asp-for="BookIds" value="@Model.BookClusters[i][j].BookId" hidden />
                            <input class="@("cluster" + i) @("checkHidden" + i + j)" name="BookChecksInt" asp-for="BookChecksInt" value="@((Model.BookChecks[i]) ? 1 : -1)" hidden />
                        }
                    }
                    <button type="submit" class="rounded btn btn-dark">Добавить</button>
                </form>
            </div>
            <div id="delete" class="mt-2" style="display:none;">
                <form asp-controller="Cluster" asp-action="DeleteTags" method="post">
                    @foreach (var tag in Model.Tags)
                    {
                        <input asp-for="TagIds" value="@tag.Id" hidden />
                        <input class="@("tagCheckHidden" + tag.Id)" name="TagChecksInt" asp-for="TagChecksInt" value="-1" hidden />
                        <div class="d-flex flex-row align-items-center mb-2">
                            <div><input type="checkbox" class="form-control @("addCheckbox" + tag.Id)" onclick="addTagCheckChange('@tag.Id')" style="width:50px;" /></div>
                            <div><label>@tag.Name</label></div>
                        </div>
                    }
                    @for (int i = 0; i < Model.BookClusters.Count; i++)
                    {
                        for (int j = 0; j < Model.BookClusters[i].Count; j++)
                        {
                            <input asp-for="ClusterIds" value="@i" hidden />
                            <input asp-for="BookIds" value="@Model.BookClusters[i][j].BookId" hidden />
                            <input class="@("cluster" + i) @("checkHidden" + i + j)" name="BookChecksInt" asp-for="BookChecksInt" value="@((Model.BookChecks[i]) ? 1 : -1)" hidden />
                        }
                    }
                    <button type="submit" class="rounded btn btn-dark">Удалить</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function showAdd() {
            document.getElementById("add").style.display = "block";
            document.getElementById("delete").style.display = "none";
        }

        function showDelete() {
            document.getElementById("delete").style.display = "block";
            document.getElementById("add").style.display = "none";
        }

        function checkChange(number) {
            document.getElementsByClassName("checkHidden" + number)[0].value *= -1;
            document.getElementsByClassName("checkHidden" + number)[1].value *= -1;
        }

        function addTagCheckChange(number) {
            document.getElementsByClassName("tagCheckHidden" + number)[0].value *= -1;
            document.getElementsByClassName("tagCheckHidden" + number)[1].value *= -1;

            document.getElementsByClassName("deleteCheckbox" + number)[0].checked = !document.getElementsByClassName("deleteCheckbox" + number)[0].checked;
        }

        function deleteTagCheckChange(number) {
            document.getElementsByClassName("tagCheckHidden" + number)[0].value *= -1;
            document.getElementsByClassName("tagCheckHidden" + number)[1].value *= -1;

            document.getElementsByClassName("addCheckbox" + number)[0].checked = !document.getElementsByClassName("addCheckbox" + number)[0].checked;
        }

        function ChangeAll(number) {
            var boolValue = document.getElementsByName("cluster" + number)[0].checked;
            var listOfInputs = document.getElementsByClassName("cluster" + number);

            for (var i = 0; i < listOfInputs.length; i++) {
                if (boolValue)
                    listOfInputs[i].value = 1;
                else
                    listOfInputs[i].value = -1;
            }
        }

        $(document).on('change', 'input[type=checkbox]', function () {
            var $this = $(this), $chks = $(document.getElementsByName(this.name)), $all = $chks.filter(".chk-all");

            if ($this.hasClass('chk-all')) {
                $chks.prop('checked', $this.prop('checked'));
            } else switch ($chks.filter(":checked").length) {
                case $all.prop('checked'):
                    $all.prop('checked', false).prop('indeterminate', false);
                    break;
                case $chks.length - !!$this.prop('checked'):
                    $all.prop('checked', true).prop('indeterminate', false);
                    break;
                default:
                    $all.prop('indeterminate', true);
            }
        });
    </script>
}